name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build Windows executable
      run: |
        python build_app.py
        
    - name: Verify Windows build
      run: |
        if (Test-Path "dist/PDFUtilities.exe") {
          Write-Host "Windows executable created successfully"
          Get-Item "dist/PDFUtilities.exe" | Select-Object Name, Length
        } else {
          Write-Error "Windows executable not found"
          exit 1
        }
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFUtilities-Windows
        path: dist/PDFUtilities.exe
        retention-days: 30

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1 libglib2.0-0 libx11-6 libxext6 libxrender1 libxtst6 libxi6 libegl1 libegl-mesa0
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build Linux executable
      run: |
        python build_app.py
        
    - name: Verify Linux build
      run: |
        if [ -f "dist/PDFUtilities" ]; then
          echo "Linux executable created successfully"
          ls -la dist/PDFUtilities
        else
          echo "Error: Linux executable not found"
          exit 1
        fi
        
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFUtilities-Linux
        path: dist/PDFUtilities
        retention-days: 30

  create-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: PDFUtilities-Windows
        path: ./windows-build
        
    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: PDFUtilities-Linux
        path: ./linux-build
        
    - name: Verify artifacts
      run: |
        echo "Verifying downloaded artifacts..."
        ls -la ./windows-build/
        ls -la ./linux-build/
        
        if [ ! -f "./windows-build/PDFUtilities.exe" ]; then
          echo "Error: Windows executable not found"
          exit 1
        fi
        
        if [ ! -f "./linux-build/PDFUtilities" ]; then
          echo "Error: Linux executable not found"
          exit 1
        fi
        
        echo "All artifacts verified successfully"
        
    - name: Create source archive
      run: |
        git archive --format=zip --output=PDFUtilities-Source.zip HEAD
        ls -la PDFUtilities-Source.zip
        
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/}
        RELEASE_NAME="PDF Utilities $VERSION"
        
        echo "Creating release for version: $VERSION"
        
        # Create release using GitHub CLI
        gh release create $VERSION \
          --title "$RELEASE_NAME" \
          --notes "## PDF Utilities $VERSION
        
        ### Features
        - PDF to DOCX conversion
        - PDF compression with multiple quality levels
        - PDF merging
        - PDF splitting
        - Text extraction
        - PDF to image conversion
        
        ### Downloads
        - Windows executable
        - Linux executable
        - Source code
        
        ### System Requirements
        - Windows 10+ or Linux
        - Python 3.11+ (for source installation)
        
        ### Installation
        Download the appropriate executable for your platform and run it directly." \
          --draft=false \
          --prerelease=false
        
        echo "Release created successfully"
        
    - name: Upload Windows executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "Uploading Windows executable for version: $VERSION"
        gh release upload $VERSION ./windows-build/PDFUtilities.exe --clobber
        echo "Windows executable uploaded successfully"
        
    - name: Upload Linux executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "Uploading Linux executable for version: $VERSION"
        gh release upload $VERSION ./linux-build/PDFUtilities --clobber
        echo "Linux executable uploaded successfully"
        
    - name: Upload source code
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "Uploading source code for version: $VERSION"
        gh release upload $VERSION ./PDFUtilities-Source.zip --clobber
        echo "Source code uploaded successfully"
        
    - name: Verify release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "Verifying release assets for version: $VERSION"
        gh release view $VERSION --json assets --jq '.assets[].name'
        echo "Release verification completed" 