name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build Windows executable
      run: |
        python build_app.py
        
    - name: Verify Windows build
      run: |
        if (Test-Path "dist/PDFUtilities.exe") {
          Write-Host "Windows executable created successfully"
          Get-Item "dist/PDFUtilities.exe" | Select-Object Name, Length
        } else {
          Write-Error "Windows executable not found"
          exit 1
        }
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFUtilities-Windows
        path: dist/PDFUtilities.exe
        retention-days: 30

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1 libglib2.0-0 libx11-6 libxext6 libxrender1 libxtst6 libxi6 libegl1 libegl-mesa0
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build Linux executable
      run: |
        python build_app.py
        
    - name: Verify Linux build
      run: |
        if [ -f "dist/PDFUtilities" ]; then
          echo "Linux executable created successfully"
          ls -la dist/PDFUtilities
        else
          echo "Error: Linux executable not found"
          exit 1
        fi
        
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFUtilities-Linux
        path: dist/PDFUtilities
        retention-days: 30

  # build-linux-arm:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #       with:
  #         platforms: arm64
  #     - name: Build ARM64 binary in Docker
  #       run: |
  #         docker run --rm --platform linux/arm64 \
  #           -v ${{ github.workspace }}:/workspace \
  #           -w /workspace \
  #           arm64v8/python:3.11 \
  #           /bin/bash -c "\
  #             apt-get update && \
  #             apt-get install -y libgl1 libglib2.0-0 libx11-6 libxext6 libxrender1 libxtst6 libxi6 libegl1 libegl-mesa0 && \
  #             pip install --upgrade pip && \
  #             pip install -r requirements.txt && \
  #             pip install pyinstaller && \
  #             python build_app.py\
  #           "
  #     - name: Upload Linux ARM artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: PDFUtilities-Linux-arm64
  #         path: dist/PDFUtilities*
  #         retention-days: 30
  #         if-no-files-found: warn

  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        # Install Homebrew if not already available
        if ! command -v brew &> /dev/null; then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
        
        # Install required system libraries
        brew install libpng jpeg zlib
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build macOS executable
      run: |
        echo "Building macOS executable..."
        echo "Current directory: $(pwd)"
        echo "Python version: $(python --version)"
        echo "Architecture: $(uname -m)"
        
        # Check if spec file exists
        if [ ! -f "pdf_utility.spec" ]; then
          echo "❌ Error: pdf_utility.spec not found!"
          echo "Available files:"
          ls -la
          exit 1
        fi
        
        echo "✅ pdf_utility.spec found"
        
        # Run the standard build script
        echo "Running build_app.py..."
        python build_app.py
        
        # Check build result
        BUILD_EXIT_CODE=$?
        echo "Build exit code: $BUILD_EXIT_CODE"
        
        if [ $BUILD_EXIT_CODE -ne 0 ]; then
          echo "❌ Build failed with exit code: $BUILD_EXIT_CODE"
          echo "Contents of current directory:"
          ls -la
          if [ -d "build" ]; then
            echo "Contents of build directory:"
            ls -la build/
          fi
          if [ -d "dist" ]; then
            echo "Contents of dist directory:"
            ls -la dist/
          fi
          exit 1
        fi
        
        echo "✅ macOS build completed successfully"
        
    - name: Verify macOS build
      run: |
        echo "Verifying macOS build..."
        echo "Contents of current directory:"
        ls -la
        
        if [ -d "dist" ]; then
          echo "Contents of dist directory:"
          ls -la dist/
        else
          echo "❌ dist directory not found"
          exit 1
        fi
        
        if [ -f "dist/PDFUtilities" ]; then
          echo "✅ macOS executable file found"
          echo "File information:"
          file dist/PDFUtilities
          echo "Architecture information:"
          lipo -info dist/PDFUtilities || echo "lipo info not available"
          echo "File size:"
          ls -lh dist/PDFUtilities
          echo "✅ macOS build verification complete"
        else
          echo "❌ macOS executable file not found"
          echo "Available items in dist:"
          ls -la dist/
          exit 1
        fi
        
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFUtilities-macOS
        path: dist/PDFUtilities
        retention-days: 30
      if: always() && hashFiles('dist/PDFUtilities/**') != ''

  create-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: PDFUtilities-Windows
        path: ./windows-build
        
    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: PDFUtilities-Linux
        path: ./linux-build
        
    # - name: Download Linux ARM artifact
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: PDFUtilities-Linux-arm64
    #     path: ./linux-arm-build
        
    - name: Download macOS artifact
      uses: actions/download-artifact@v4
      with:
        name: PDFUtilities-macOS
        path: ./macos-build
      continue-on-error: true
        
    - name: Verify artifacts
      run: |
        echo "Verifying downloaded artifacts..."
        
        # Check Windows
        if [ -d "./windows-build" ]; then
          ls -la ./windows-build/
          if [ ! -f "./windows-build/PDFUtilities.exe" ]; then
            echo "❌ Error: Windows executable not found"
            exit 1
          fi
          echo "✅ Windows build verified"
        else
          echo "❌ Windows build directory not found"
          exit 1
        fi
        
        # Check Linux
        if [ -d "./linux-build" ]; then
          ls -la ./linux-build/
          if [ ! -f "./linux-build/PDFUtilities" ]; then
            echo "❌ Error: Linux executable not found"
            exit 1
          fi
          echo "✅ Linux build verified"
        else
          echo "❌ Linux build directory not found"
          exit 1
        fi
        
        # Check Linux ARM - DISABLED
        # if [ -d "./linux-arm-build" ]; then
        #   echo "✅ Linux ARM build directory found"
        #   echo "Contents of linux-arm-build:"
        #   ls -la ./linux-arm-build/
        #   
        #   if [ -f "./linux-arm-build/PDFUtilities" ]; then
        #     echo "✅ Linux ARM executable found"
        #     echo "File information:"
        #     file ./linux-arm-build/PDFUtilities
        #     echo "Architecture information:"
        #     lipo -info ./linux-arm-build/PDFUtilities || echo "lipo info not available"
        #     echo "✅ Linux ARM build verified"
        #   else
        #     echo "❌ PDFUtilities executable not found in linux-arm-build directory"
        #     echo "Available files:"
        #     ls -la ./linux-arm-build/
        #     exit 1
        #   fi
        # else
        #   echo "❌ Linux ARM build directory not found"
        #   echo "Available directories:"
        #   ls -la ./
        #   exit 1
        # fi
        
        # Check macOS (should be a single executable file)
        if [ -d "./macos-build" ]; then
          echo "✅ macOS build directory found"
          echo "Contents of macos-build:"
          ls -la ./macos-build/
          
          if [ -f "./macos-build/PDFUtilities" ]; then
            echo "✅ macOS executable found"
            echo "File information:"
            file ./macos-build/PDFUtilities
            echo "Architecture information:"
            lipo -info ./macos-build/PDFUtilities || echo "lipo info not available"
            echo "✅ macOS build verified"
          else
            echo "❌ PDFUtilities executable not found in macos-build directory"
            echo "Available files:"
            ls -la ./macos-build/
            exit 1
          fi
        else
          echo "❌ macOS build directory not found"
          echo "Available directories:"
          ls -la ./
          exit 1
        fi
        
        echo "✅ All required artifacts verified successfully"
        
    - name: Create source archive
      run: |
        git archive --format=zip --output=PDFUtilities-Source.zip HEAD
        ls -la PDFUtilities-Source.zip
        
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/}
        RELEASE_NAME="PDF Utilities $VERSION"
        
        echo "Creating release for version: $VERSION"
        
        # Create release using GitHub CLI
        gh release create $VERSION \
          --title "$RELEASE_NAME" \
          --notes "## PDF Utilities $VERSION
        
        ### Features
        - PDF to DOCX conversion
        - PDF compression with multiple quality levels
        - PDF merging
        - PDF splitting
        - Text extraction
        - PDF to image conversion
        
        ### Downloads
        - **Windows (x64)**: PDFUtilities-Windows-x64.exe
        - **Linux (x64)**: PDFUtilities-Linux-x64
        - **macOS (Apple Silicon)**: PDFUtilities-macOS-arm64
        - **Source code**: PDFUtilities-Source.zip
        
        ### System Requirements
        - **Windows**: Windows 10+ (x64)
        - **Linux**: Ubuntu 18.04+ or equivalent (x64)
        - **macOS**: macOS 10.15+ with Apple Silicon (M1/M2/M3) processors
        - **Source**: Python 3.11+ (for source installation)
        
        ### Installation
        1. Download the appropriate executable for your platform
        2. Make it executable (Linux/macOS): \`chmod +x PDFUtilities-*\`
        3. Run the executable directly
        
        ### Notes
        - **macOS**: This build is optimized for Apple Silicon Macs (M1/M2/M3)
        - **macOS**: Intel Mac users should use the source installation
        - **macOS**: May require security permissions on first run (System Preferences > Security & Privacy)
        - **Linux**: Tested on Ubuntu 20.04+, should work on most modern distributions
        - **Windows**: No additional dependencies required" \
          --draft=false \
          --prerelease=false
        
        echo "Release created successfully"
        
    - name: Upload Windows executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "Uploading Windows executable for version: $VERSION"
        # Rename the Windows executable to include OS and architecture
        cp ./windows-build/PDFUtilities.exe ./PDFUtilities-Windows-x64.exe
        gh release upload $VERSION ./PDFUtilities-Windows-x64.exe --clobber
        echo "Windows executable uploaded successfully as PDFUtilities-Windows-x64.exe"
        
    - name: Upload Linux executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "Uploading Linux executable for version: $VERSION"
        # Rename the Linux executable to include OS and architecture
        cp ./linux-build/PDFUtilities ./PDFUtilities-Linux-x64
        gh release upload $VERSION ./PDFUtilities-Linux-x64 --clobber
        echo "Linux executable uploaded successfully as PDFUtilities-Linux-x64"
        
    # - name: Upload Linux ARM executable
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     VERSION=${GITHUB_REF#refs/tags/}
    #     echo "Uploading Linux ARM executable for version: $VERSION"
    #     cp ./linux-arm-build/PDFUtilities ./PDFUtilities-Linux-arm64
    #     gh release upload $VERSION ./PDFUtilities-Linux-arm64 --clobber
    #     echo "Linux ARM executable uploaded successfully as PDFUtilities-Linux-arm64"
        
    - name: Upload macOS executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "Uploading macOS executable for version: $VERSION"
        # Rename the macOS executable to include OS and architecture
        cp ./macos-build/PDFUtilities ./PDFUtilities-macOS-arm64
        gh release upload $VERSION ./PDFUtilities-macOS-arm64 --clobber
        echo "macOS executable uploaded successfully as PDFUtilities-macOS-arm64"
        
    - name: Upload source code
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "Uploading source code for version: $VERSION"
        gh release upload $VERSION ./PDFUtilities-Source.zip --clobber
        echo "Source code uploaded successfully"
        
    - name: Verify release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "Verifying release assets for version: $VERSION"
        gh release view $VERSION --json assets --jq '.assets[].name'
        echo "Release verification completed" 